name: Generate changelog
on: push
jobs:
  generate_changelog:
    runs-on: ubuntu-latest
    name: Generate changelog for master branch
    if: "contains(github.event.head_commit.message, '[maven-release-plugin] prepare for next development iteration')"
    steps:
      - uses: actions/checkout@v1
      - name: Generate changelog
        run: |
          git log --date=short --pretty="- %cd:%an - %s" > changelog.md
      - name: Commit files
        run: |
          git config --local user.email "$GITHUB_ACTOR"
          git config --local user.name "$GITHUB_ACTOR@github.com"
          git add changelog.md && git commit -m '[ci skip] Updated CHANGELOG.md'
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" HEAD:$GITHUB_REF